### ISSUE TITLE
Docker 1.13 stack issue

### ISSUE THREAD

**Issue by CyrilPeponnet** [ContainX/docker-volume-netshare#101]
As 0.33 is not working with swarm, I'm using 0.32 and also tried with master.

While it works fine wit simple docker run like:

```
core@localhost ~ $ docker run -i -t --volume-driver=nfs -v server/share:/test busybox ls /test | wc -l
core@localhost ~ $ 17
```

With debug:

```
DEBU[1463] Entering Get: {server/share map[]}
DEBU[1463] Get: mount found for server/share, host directory: /var/lib/docker-volumes/netshare/nfs/server:share
DEBU[1463] Host path for server/share (server/share) is at /var/lib/docker-volumes/netshare/nfs/server/share
DEBU[1463] Entering Mount: {server:share 561289a23a48c625c1bad39f62700a6a5ff56e69f00b36114a897adf57176234}
INFO[1463] Mounting NFS volume server:/share on /var/lib/docker-volumes/netshare/nfs/server:share
DEBU[1463] Mounting with NFSv3 - src: server:/share, dest: /var/lib/docker-volumes/netshare/nfs/server:share
DEBU[1463] exec: mount -v -t nfs -o port=2049,nolock,proto=tcp server:/share /var/lib/docker-volumes/netshare/nfs/server:share
DEBU[1468] Entering Unmount: {server:share 561289a23a48c625c1bad39f62700a6a5ff56e69f00b36114a897adf57176234}
INFO[1468] Unmounting volume name server:share from /var/lib/docker-volumes/netshare/nfs/server:share
```

Using a simple stack like:

```yaml
version: "3"
services:
  test:
    image: busybox
    deploy:
      replicas: 1
    volumes:
      - share:/test
    command: ls /test/ | wc -l


volumes:
  share:
    driver: nfs
    driver_opts:
      share: server:/share
```

Deployed with `docker stack deploy -c test.yaml test` gives me:

```
DEBU[1802] Entering Get: {test_share map[]}
DEBU[1802] Entering Create: name: test_share, options map[share:sever:/share]
DEBU[1802] Create volume -> name: test_share, map[share:sever:/share]
DEBU[1802] Host path for test_share (test_share) is at /var/lib/docker-volumes/netshare/nfs/test_share
DEBU[1802] Entering Get: {test_share map[]}
DEBU[1802] Get: mount found for test_share, host directory: /var/lib/docker-volumes/netshare/nfs/test_share
DEBU[1803] Entering Get: {test_share map[]}
DEBU[1803] Get: mount found for test_share, host directory: /var/lib/docker-volumes/netshare/nfs/test_share
DEBU[1803] Entering Get: {test_share map[]}
DEBU[1803] Get: mount found for test_share, host directory: /var/lib/docker-volumes/netshare/nfs/test_share
```

and `docker stack ps test --no-trunc`

```
docker stack ps test --no-trunc
ID                         NAME             IMAGE                                                                                   NODE       DESIRED STATE  CURRENT STATE            ERROR                                                                 PORTS
swk3rqayt02k0ydrd0whrd5cb  test_test.1      busybox:latest@sha256:817a12c32a39bbe394944ba49de563e085f1d3c5266eb8e9723256bc4448680e  localhost  Ready          Rejected 2 seconds ago   "SELinux relabeling of  is not allowed: "no such file or directory""
n6q74tfeilwwdplb9gvsirpgy   \_ test_test.1  busybox:latest@sha256:817a12c32a39bbe394944ba49de563e085f1d3c5266eb8e9723256bc4448680e  localhost  Shutdown       Rejected 7 seconds ago   "SELinux relabeling of  is not allowed: "no such file or directory""
ebb4b02yabfaxb8ur5aby248t   \_ test_test.1  busybox:latest@sha256:817a12c32a39bbe394944ba49de563e085f1d3c5266eb8e9723256bc4448680e  localhost  Shutdown       Rejected 12 seconds ago  "SELinux relabeling of  is not allowed: "no such file or directory""
ru8n97cekzpphaciqca5g1sde   \_ test_test.1  busybox:latest@sha256:817a12c32a39bbe394944ba49de563e085f1d3c5266eb8e9723256bc4448680e  localhost  Shutdown       Rejected 17 seconds ago  "SELinux relabeling of  is not allowed: "no such file or directory""
qa4nvp5vayhu6vzo1ehinngsq   \_ test_test.1  busybox:latest@sha256:817a12c32a39bbe394944ba49de563e085f1d3c5266eb8e9723256bc4448680e  localhost  Shutdown       Rejected 22 seconds ago  "SELinux relabeling of  is not allowed: "no such file or directory""
```

from docker logs

```
Feb 09 22:27:08 localhost dockerd[3802]: time="2017-02-09T22:27:08.602508999Z" level=error msg="fatal task error" error="SELinux relabeling of  is not allowed: \"no such file or directory\"" module="node/agent/taskmanager" task.id=rj6tm0frsa5q73zkh0btkr80z
Feb 09 22:27:09 localhost dockerd[3802]: time="2017-02-09T22:27:09.004607096Z" level=error msg="failed to deactivate service binding for container test_test.1.qirezacdc26fuip14nl0jsjm3" error="No such container: test_test.1.qirezacdc26fuip14nl0jsjm3" module="node/agent"
Feb 09 22:27:14 localhost dockerd[3802]: time="2017-02-09T22:27:14.042922214Z" level=error msg="failed to deactivate service binding for container test_test.1.mmi1pebgvle2otv74qoaltg96" error="No such container: test_test.1.mmi1pebgvle2otv74qoaltg96" module="node/agent"
Feb 09 22:27:18 localhost dockerd[3802]: time="2017-02-09T22:27:18.619736983Z" level=error msg="fatal task error" error="SELinux relabeling of  is not allowed: \"no such file or directory\"" module="node/agent/taskmanager" task.id=vbg26wmccxhfztvo4eoq203cc
```

from `docker volume inspect test_share`

```
[
    {
        "Driver": "nfs",
        "Labels": {
            "com.docker.stack.namespace": "test"
        },
        "Mountpoint": "/var/lib/docker-volumes/netshare/nfs/test_share",
        "Name": "test_share",
        "Options": {
            "share": "server:/share"
        },
        "Scope": "local"
    }
]
```

Something is getting stripped at some point I think...

**Comment by CyrilPeponnet** [comment]
It looks like docker never call `VolumeDriver.Mount` when using a stack.

**Comment by CyrilPeponnet** [comment]
Maybe stacks are not designed to create / mount storage on docker nodes... I cannot find any relevant info about it.

**Comment by gondor** [comment]
I'm currently in the process of refactoring the plugin for Docker 1.13+.  There have been a lot of changes since the original Docker plugin API.   I'm tracking this effort in this issue: https://github.com/ContainX/docker-volume-netshare/issues/102

**Comment by sigoden** [comment]
Manual create volume on each node will work; It seems the docker swarm failed to create volume on the work node;

**Comment by jkirkby91-2** [comment]
+1 i believe i'm having the same issue when im running docker stack deploy it creates my networks but no volumes

**Comment by jkirkby91-2** [comment]
@sigoden have you an example command to create these

**Comment by CyrilPeponnet** [comment]
`docker volume create --driver local --opt type=nfs --opt o=addr=IP --opt device=:/share --name foo` with builtin docker or `$ docker volume create -d nfs --name myvol -o share=nfshost:/share` with netshare (see http://netshare.containx.io/docs/nfs).

**Comment by jkirkby91-2** [comment]
@CyrilPeponnet 

when running 

root@qg-node-1:~# docker volume create -d nfs --name=qg-queue -o share=10.131.1.50:/srv/qg-queue

i get this error

Error response from daemon: create qg-queue: create qg-queue: Error looking up volume plugin nfs: legacy plugin: Post http://%2Frun%2Fdocker%2Fplugins%2Fnfs.sock/Plugin.Activate: dial unix /run/docker/plugins/nfs.sock: connect: connection refused.

The other command is no good as docker swarm wont deploy containers across swarm hosts if the volume driver is local

**Comment by jkirkby91-2** [comment]
@CyrilPeponnet 

when running 

root@qg-node-1:~# docker volume create -d nfs --name=qg-queue -o share=10.131.1.50:/srv/qg-queue

i get this error

Error response from daemon: create qg-queue: create qg-queue: Error looking up volume plugin nfs: legacy plugin: Post http://%2Frun%2Fdocker%2Fplugins%2Fnfs.sock/Plugin.Activate: dial unix /run/docker/plugins/nfs.sock: connect: connection refused.

when i run 

docker volume create --driver local --opt type=nfs --opt o=addr=10.131.1.50 --opt device=:/srv/qg-queue --name qg-queue-fpm-nfs
it creates my volume

[
    {
        "Driver": "local",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/volumes/qg-queue-fpm-nfs/_data",
        "Name": "qg-queue-fpm-nfs",
        "Options": {
            "device": ":/srv/qg-queue",
            "o": "addr=10.131.1.50",
            "type": "nfs"
        },
        "Scope": "local"
    }
]

in my docker compose it hen have

volumes:
  qg-queue-fpm-nfs:
    external: true 

  qg-queue-fpm:
    image /qg/queue-fpm      
    volumes:
      - qg-queue-fpm-nfs:/srv/www

If i then enter the container to the directory nothing is there :(
