### ISSUE TITLE
Documentation links to old release

### ISSUE THREAD

**Issue by am0s** [ContainX/docker-volume-netshare#146]
The installation refers to the 0.20 release while the latest release (as of this moment) is 0.34.

I'm assuming the documentation is not updated, or is there a reason for not using the latest release?

**Comment by elijah** [comment]
Fixed in https://github.com/ContainX/docker-volume-netshare/pull/152 - waiting on upstream to accept and merge.

**Comment by gondor** [comment]
Website now reflects latest version - `0.35`.  Thanks for pointing this out
