### ISSUE TITLE
Wrong path to EnvironmentFile

### ISSUE THREAD

**Issue by am0s** [ContainX/docker-volume-netshare#147]
The *docker-volume-netshare.service* defines the *EnvironmentFile* as `/etc/sysconfig/docker-volume-netshare` while the debian package installs it in `/etc/default/docker-volume-netshare`.
Without this fix the service will not start on Debian/Ubuntu.

Is the path wrong or is this a difference between Debian/Ubuntu and other systems?

**Comment by gondor** [comment]
Can you post the service file you're using?

**Comment by gondor** [comment]
Closing due to time lapse
