### ISSUE TITLE
EFS --noresolve seems to not work properly

### ISSUE THREAD

**Issue by konstl000** [ContainX/docker-volume-netshare#164]
If IP addresses are provided instead of file system IDs, the plugin runs:
exec: mount -t nfs4 -o nfsvers=4.1 : /path/to/share

This seems to be caused by:
reg, _ := regexp.Compile("(fs-[0-9a-f]+)$") (line 106 in /drivers/efs.go)
uri := reg.FindString(v[0])

As far as I understand, this check does not make much sense because if --noresolve is not set, the value of uri generated as above is not used at all because it is then defined here:
uri = fmt.Sprintf(EfsTemplateURI, v[0], e.region)  (line 110)

On the other hand, if --noresolve is set, the code above sets uri to "" which in turn results in the execution of
mount -t nfs4 -o nfsvers=4.1 : /path/to/share
instead of mount -t nfs4 -o nfsvers=4.1 123.456.78.9: /path/to/share

If the line 106 is substituted by
reg, _ := regexp.Compile("([0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+)$")
The plugin works as expected in --noresolve mode.

**Comment by gondor** [comment]
added fix based on suggestion
