### ISSUE TITLE
nfs error when restart the docker service 

### ISSUE THREAD

**Issue by ivanjz93** [ContainX/docker-volume-netshare#168]
When I restart the docker service with nfs driver mount:
`"Mounts": [
                        {
                            "Type": "volume",
                            "Source": "jupyterhub-user-huangzhe",
                            "Target": "/home/jovyan/work",
                            "VolumeOptions": {
                                "DriverConfig": {
                                    "Name": "nfs",
                                    "Options": {
                                        "share": "3c0e84962e-www82.cn-shanghai.nas.aliyuncs.com:/huangzhe"
                                    }
                                }
                            }
                        }
                    ]`

The update operation did nothing with mounts options. I just update the resource limit:

`"Resources": {
                    "Limits": {
                        "NanoCPUs": 1000000000,
                        "MemoryBytes": 2147483648
                    }
                }`

I got an error:

> create jupyterhub-user-huangzhe: found references to volume 'jupyterhub-user-huangzhe' in driver 'nfs' but the volume was not found in the driver -- you may need to remove containers referencing this volume or force remove the volume to re-create it: volume name must be unique"

**Comment by jakirpatel** [comment]
@ivanjz93 

Please check my PR to resolve this issue. 

Jakir.
