### ISSUE TITLE
NFS volumes gone after reboot

### ISSUE THREAD

**Issue by lqb** [ContainX/docker-volume-netshare#33]
I have created some NFS volumes. After rebooting this volumes aren't listed in docker volume ls.
Containers using this volumes can't be started because the volumes don't exist.

I am using Ubuntu 14.04 with docker 1.10.3 and docker-volume-netshare 0.16

**Comment by holgerreif** [comment]
The mounts are not persisted in /etc/fstab, rather done dynamically as requested by docker daemon. So it's expected they are gone after reboot.

So you should use `docker volume create` after reboot and then the volume is available again.
If you don't use the `share=` option you should even be able to use the volume because it gets mounted w/o explicitely creating it before.

If you need further advise please post how you create the volume before mount and what you actually do after reboot together with `docker-volume-netshare` logs before and after reboot.

**Comment by lqb** [comment]
What do you mean with `share=` option and where do I have to disable it?

I use `docker volume  create --driver nfs --name $(hostname)/volumes/some-volume` to create a volume

**Comment by holgerreif** [comment]
> What do you mean with share= option and where do I have to disable it?

The you probably don't use this option.

Again, please provide the exact commands before and after reboot and provide the logs from `docker-volume-netshare` before and after reboot.

**Comment by gondor** [comment]
Closing this.  Will incorporate #35 suggestion into repo

**Comment by jcosmo** [comment]
Is this a particular excentricity of this particular volume driver, or do all work like this?

After a reboot of the host machine docker engine restarts, the docker-volume-netshare service restarts, and docker engine attempts to restart all the containers, but the volumes are not auto recreated, which means that the containers with NFS volume dependencies fail to create.

**Comment by manast** [comment]
@jcosmo this is a limitation/feature of docker... AFAIK you need to create the volumes in the service create command so that they will be recreated when rebooting, but I have not tested this yet.

**Comment by abrari** [comment]
Any idea on how to recreate the NFS volume automatically before the container that depends on it started?

**Comment by manast** [comment]
@abrari you should make it work by using the --mount flag when creating the service giving it all the volume arguments needed: https://docs.docker.com/engine/reference/commandline/service_create/

**Comment by buster3** [comment]
I have the same issue.
Currently i use:
```
docker run -d -p 5000:5000 --restart=unless-stopped --name registry \
  --volume-driver=nfs \
  -v 192.168.3.203/BuildStorage/dockerRegistry:/var/lib/registry \
  registry:2
```
After a reboot all volumes are gone 
```
Error response from daemon: get 192.168.3.203/BuildStorage/dockerRegistry:/var/lib/registry: no such volume
```

Do i have to use docker service?
