### ISSUE TITLE
"docker volume ls" with spureous warning/error

### ISSUE THREAD

**Issue by joaocc** [ContainX/docker-volume-netshare#39]
Hi,
I have docker-volume-netshare installed, with this content in ```/etc/default/docker-volume-netshare```
```
DKV_NETSHARE_OPTS="cifs"
```
I also installed cifs-utils only on Ubuntu 16.04, with docker 1.11.
```
$ sudo docker volume ls
list nfs: Post http://%2Frun%2Fdocker%2Fplugins%2Fnfs.sock/VolumeDriver.List: dial unix /run/docker/plugins/nfs.sock: connect: connection refused
DRIVER              VOLUME NAME
```
I tried installing nfs-common and the message persists.
Any idea on how to get rid of this message?
Besides the aesthetics, it add a 15s delay to a simple "docker volume ls".
Thx

**Comment by holgerreif** [comment]
The problem probably is, you once started the plugin with `DKV_NETSHARE_OPTS="nfs"` which created the `/run/docker/plugins/nfs.sock` socket.

Simply remove this file (it is recreated at startup with option set to nfs mode in case you need it in future) by
```rm /run/docker/plugins/nfs.sock```

**Comment by joaocc** [comment]
That solved it. Thx
