### ISSUE TITLE
EFS path is not mounted, only rootpath

### ISSUE THREAD

**Issue by slhad** [ContainX/docker-volume-netshare#46]
Hello,

When I use configure a volume with EFS for ex : 
`--volume-driver=efs -v fs-aaaa1234/folders:/folders`

The mount cmd is :
`mount -t nfs4 10.100.0.100:/ /var/lib/docker-volumes/netshare/efs/fs-aaaa1234/folders`

This problem of path is not reproductible with --volume-driver=nfs :
`--volume-driver=nfs -v 10.100.0.100/folders:/folders`

give the mound cmd :
`mount -v -t nfs4 10.100.0.100:/folders /var/lib/docker-volumes/netshare/nfs/10.100.0.100/folders`

Are subpath (like fs-aaaa1234/folders) for EFS supported ?

**Comment by ephillipe** [comment]
I'm using 0.19 release but error persist. I can't get mount on subpath.

```
time="2016-07-14T14:05:29Z" level=error msg="Error during resolve: Response was empty" 
time="2016-07-14T14:05:29Z" level=info msg="Mounting EFS volume 172.31.49.24:/pgadmin on /var/lib/docker-volumes/netshare/efs/fs-d373b79a/pgadmin" 
2016/07/14 14:05:29 mount.nfs4: mounting 172.31.49.24:/pgadmin failed, reason given by server: No such file or directory

time="2016-07-14T14:05:29Z" level=error msg="Error during resolve: Response was empty" 
time="2016-07-14T14:05:29Z" level=info msg="Unmounting volume 172.31.49.24:/pgadmin from /var/lib/docker-volumes/netshare/efs/fs-d373b79a/pgadmin" 
2016/07/14 14:05:29 umount: /var/lib/docker-volumes/netshare/efs/fs-d373b79a/pgadmin: not mounted

```

**Comment by sawanoboly** [comment]
Hi, @gondor 

0.19 causes error.

```
$ docker --debug run -it --rm --volume-driver=efs -v fs-xxxxxxx/subdir01:/mnt/data alpine /bin/sh
docker: Error response from daemon: VolumeDriver.Mount: exit status 32.

----
## subdir01 is already exist.

time="2016-08-19T06:35:48Z" level=info msg="Mounting EFS volume 192.168.34.196:/sitexxxx on /var/lib/docker-volumes/netshare/efs/fs-xxxxxxx/subdir01" 
2016/08/19 06:35:49 mount.nfs4: mounting 192.168.34.196:/subdir01 failed, reason given by server: No such file or directory
```

0.17 works fine. It creates automatically even if it is not exist.

```
$ docker run -it --rm --volume-driver=efs -v fs-xxxxxxx/subdir01:/mnt/data alpine /bin/sh
bash-4.3$ 
```

**Comment by ephillipe** [comment]
== Version: 0.32 - Built: 2016-10-10T23:03:47-07:00 ==
I'm getting error trying mount using subfolder, too.

ubuntu@ip-172-31-15-7:~$ docker run -it --volume-driver=efs -v fs-xxxxxxxx/teste:/mount ubuntu /bin/bash
docker: Error response from daemon: VolumeDriver.Mount: exit status 32.


Debug logs:
`
DEBU[0741] Host path for fs-xxxxxxxx/teste (fs-xxxxxxxx/teste) is at /var/lib/docker-volumes/netshare/efs/fs-xxxxxxxx/teste 
DEBU[0741] Attempting to resolve: us-east-1a..efs.us-east-1.amazonaws.com 
ERRO[0741] Error during resolve: Couldn't resolve name 'us-east-1a..efs.us-east-1.amazonaws.com.' : dns: bad rdata 
INFO[0741] Mounting EFS volume us-east-1a..efs.us-east-1.amazonaws.com: on /var/lib/docker-volumes/netshare/efs/fs-xxxxxxxx/teste 
DEBU[0741] exec: mount -t nfs4 -o nfsvers=4.1 us-east-1a..efs.us-east-1.amazonaws.com: /var/lib/docker-volumes/netshare/efs/fs-xxxxxxxx/teste
 
2017/01/06 17:52:16 mount.nfs4: Failed to resolve server us-east-1a..efs.us-east-1.amazonaws.com: Name or service not known

DEBU[0741] Attempting to resolve: us-east-1a..efs.us-east-1.amazonaws.com 
ERRO[0741] Error during resolve: Couldn't resolve name 'us-east-1a..efs.us-east-1.amazonaws.com.' : dns: bad rdata 
INFO[0741] Unmounting volume us-east-1a..efs.us-east-1.amazonaws.com: from /var/lib/docker-volumes/netshare/efs/fs-xxxxxxxx/teste 
2017/01/06 17:52:17 umount: /var/lib/docker-volumes/netshare/efs/fs-xxxxxxxx/teste: not mounted

DEBU[0741] Host path for fs-xxxxxxxx/teste (fs-xxxxxxxx/teste) is at /var/lib/docker-volumes/netshare/efs/fs-xxxxxxxx/teste
`
