### ISSUE TITLE
CFIS drivee does not handle options with using --name foo in conjunction with -o share=bar/bob

### ISSUE THREAD

**Issue by jcosmo** [ContainX/docker-volume-netshare#56]
The VolumeDriver creates mount points using the mountpoint name.
   v.mountm.Create(r.Name, dest, r.Options)

The CIFS driver, during the instantiation of the mount, looks up the options for a mount point using the mount 'source' aka the 'hostpath'.

The process fails when using the share option:
  docker volume create --name example -o share=foo/bar -o username=xxx -o password=pwd
The volume is stored in VolumeManager under the key "example", and looked up via the source of " '/var/lib/docker-volumes/netshare/cifs/example'".  

This results in none of the other options being applied during the call to mount.

A quick look at the code makes me think this probably doesn't work when using the following either:
   docker volume create --name foo/bar -o username=xxx -o password=pwd
The name is 'foo/bar' and the source is '/var/lib/docker-volumes/netshare/cifs/foo/bar'

Am extremely new to Go, so could be misreading this, but will have a wack at fixing the problem, unless someone points out  a mistake in the way I am using the plugin

**Comment by holgerreif** [comment]
I can confirm this bug with nfs as well:

```
# docker volume create -d nfs --name test -o share=172.17.9.33:/app/nfstest_hr -o ro
# docker run --rm --name alp -v test:/mnt -ti alpine sh -c "mount | grep nfs"
172.17.9.33:/app/nfstest_hr on /mnt type nfs (rw,relatime,vers=3,rsize=32768,wsize=32768,namlen=255,hard,nolock,proto=tcp,port=2049,timeo=600,retrans=2,sec=sys,mountaddr=172.17.9.33,mountvers=3,mountport=912,mountproto=tcp,local_lock=all,addr=172.17.9.33)
```

Actually `share` seems to be the only working Option! The following doesn't work either:

```
# docker volume create -d nfs --name 172.17.9.33/app/nfstest_hr -o ro
```

The debug log (trimmed) shows that the option is passed correctly (1st line) but the option is not applied (2nd line)

```
26T17:14:33+02:00" level=debug msg="Create volume -> name: 172.17.9.33/app/nfstest_hr, map[ro:]"
<...>
26T17:14:56+02:00" level=debug msg="exec: mount -v -o port=2049,nolock,proto=tcp 172.17.9.33:/app/nfstest_hr /var/lib/docker-volumes/netshare/nf
```

**Comment by holgerreif** [comment]
This even independent of option `--name` since [the doc ](https://docs.docker.com/v1.11/engine/reference/commandline/volume_create/) states about absence of this parameter :
_If a name is not specified, Docker generates a random name._

**Comment by gondor** [comment]
@holgerreif I'm setting up a dedicated cloud instance to test netshare whenever there's changes, new features or new version of docker.   Could you send me a few test cases using NFS you would deem a pass if they work?  I will work on CIFS after but right now focussing on NFS and want to attempt to automate this.
