### ISSUE TITLE
Error when using nfs share on docker 

### ISSUE THREAD

**Issue by little-joe999** [ContainX/docker-volume-netshare#57]
Hi,

I just came across netshare, after looking for a easy way to share directories in docker. I deployed version 0.18 on a Ubuntu 14.04 vm image and it seems that the service is running correctly. However when I want to use it i get the following error messages:

(direct usage in a container creation)
docker run -d --hostname containername.localdomain --name container1 --volume-driver=nfs -v localhost/home/app/dockerhare:/home/app/dockershare -e PORT=8081 -e HOST=containername.localdomain -e SERVER_NAME=container-server1 -p 8081:8081 app/container
docker: An error occurred trying to connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.22/containers/create?name=container: EOF.

The container gets created and after a manual start of the container I can access the container and I can see that they nfs directory got deployed correctly, however the port exposure gets ignored and ort 8081 is not available on localhost so I would have to do that manually again.

(indirect via creating a volume)
user@mesos-slave1:~/dockershare/app$ docker volume create --driver=nfs --opt share=localhost:/home/app/dockershare --name dockershare
An error occurred trying to connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.22/volumes/create: EOF

In this case the container wont get created...

user@mesos-slave1:~/dockershare/app$ docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:36:33 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:36:33 2016
 OS/Arch:      linux/amd64

Are there any known compatibility issues between 0.18 and Docker 1.10? The images have been created about 6 months ago and I have not yet upgraded the OS / docker / Mesos since everything else works very well together.

Thanks
Joe

**Comment by little-joe999** [comment]
Ok, I upgraded to docker 1.11.2 and initially I got the error message 
# docker: Error response from daemon: VolumeDriver.Mount: exit status 32.
when I try to use the volume directly but also when I tried to mount via  a volume. I could create the volume but once I wanted to mount it into the container same error appeared. My docker.service had the MoutFlag=slave set already (saw that in a previous incident).

I then realized that I tried to mount the wrong directory. I had a directory mounted via NFS locally which I wanted to use but instead I am using now the NFS server's exported directory and suddenly things worked as expected. 
This is really great and now I can use one central directory where I have all my data stored in the containers.

So this incident is solved. Sorry for opening one for this.
Joe

**Comment by holgerreif** [comment]
I'm glad you solved your problem. 
Is there a specific piece of documentation that misguided you (that we have to improve)?
