### ISSUE TITLE
v0.19 mount nfs share even if we don't have access without error message

### ISSUE THREAD

**Issue by tinsjourney** [ContainX/docker-volume-netshare#65]
Hi,

In v0.18 when we tried to mount a nfs share we don't have access we had the message and docker run command failed

```
INFO[0014] Mounting NFS volume fasparbjnmut001b:/unxprdmas/distribution/linux/as-7-u2-x86_64 on /var/lib/docker-volumes/netshare/nfs/fasparbjnmut001b/unxprdmas/distribution/linux/as-7-u2-x86_64
2016/08/18 15:50:54 mount.nfs: access denied by server while mounting fasparbjnmut001b:/unxprdmas/distribution/linux/as-7-u2-x86_64
INFO[0014] Unmounting volume name fasparbjnmut001b/unxprdmas/distribution/linux/as-6-u7-x86_64 from /var/lib/docker-volumes/netshare/nfs/fasparbjnmut001b/unxprdmas/distribution/linux/as-6-u7-x86_64
2016/08/18 15:50:54 umount: /var/lib/docker-volumes/netshare/nfs/fasparbjnmut001b/unxprdmas/distribution/linux/as-6-u7-x86_64: not mounted
docker: Error response from daemon: VolumeDriver.Mount: exit status 32.
```

But now in v0.19, the container start and we don't have any error messages.
```
INFO[0014] Mounting NFS volume fasparbjnmut001b:/unxprdmas/distribution/linux/as-7-u2-x86_64 on /var/lib/docker-volumes/netshare/nfs/fasparbjnmut001b/unxprdmas/distribution/linux/as-7-u2-x86_64
INFO[0014] Mounting NFS volume fasparbjnmut001b:/unxprdmas/distribution/linux/as-6-u7-x86_64 on /var/lib/docker-volumes/netshare/nfs/fasparbjnmut001b/unxprdmas/distribution/linux/as-6-u7-x86_64 
```
The mount point is created in our container but there is nothing inside obviously.

I'm using the following command to start docker-volume-netshare (depend on the version)
```./docker-volume-netshare_0.{18|19}_linux_amd64-bin nfs -v 3```

to start my container  I add

```
--volume-driver=nfs
-v fasparbjnmut001b/unxprdmas/distribution/linux/as-7-u2-x86_64:/UNXTSTMAS/distribution/linux/as-7-u2-x86_64:ro
-v fasparbjnmut001b/unxprdmas/distribution/linux/as-6-u7-x86_64:/UNXTSTMAS/distribution/linux/as-6-u7-x86_64:ro
```

to my docker run command.

Is there anyway to put back the v0.18 behaviour ?

Thanks.

**Comment by gondor** [comment]
Do you have an environment (Golang) setup where you could clone and build a local binary?  If so, curious to see if this PR fixes before I try to diff for the cause.  You could clone the branch from the user in this PR to test.  Let me know :)  https://github.com/ContainX/docker-volume-netshare/pull/58

**Comment by tinsjourney** [comment]
Same issue with this PR.

**Comment by tinsjourney** [comment]
you can ignore the issue, the trouble was with nfs routing not allowed between the two servers.
I confirm it's working with v0.19, we have the alert message when not allowed.
Sorry for the noise.
