### ISSUE TITLE
[question] Difference between using a mounted NFS directory vs netshare plugin

### ISSUE THREAD

**Issue by manast** [ContainX/docker-volume-netshare#66]
I have been using local volumes before, in a docker environment without using swarm. Now I started a new project with a swarm cluster and I am exploring my options. A shared NFS share seems like a quite simple setup, that will work as long as I do not care having the storage as my SPOF.
Since I used a NFS mounted directory before without using any plugin and it worked well, I am wondering, what are the benefits of using the netshare plugin? what can I do with it that its not possible or inconvenient to do without it just creating a local docker volume using the path to the mounted NFS share?

**Comment by gondor** [comment]
For a single application host-level NFS volumes are probably ok.   But once you start running many different applications/services and you want them to have their own "storage" it becomes a management nightmare.  This the plugin links the volume within the container thats requesting it.
