### ISSUE TITLE
0.20 deb package overwrites /etc/default/docker-volume-netshare

### ISSUE THREAD

**Issue by sawanoboly** [ContainX/docker-volume-netshare#69]
Hi,

I've upgrade docker-volume-netshare from 0.19 to 0.20 by deb package. Maybe, this process overwrites my `/etc/default/docker-volume-netshare` ?

Please consider using conffiles feature to create package.

**Comment by gondor** [comment]
We're using Goxc to build the binaries.  Feel free to create a PR if you know how to address this. The config is driven from the Makefile and `.goxc.json`.  I will look into it soon when I get a cycle if not.
