### ISSUE TITLE
No ARM build for latest version

### ISSUE THREAD

**Issue by Lindenk** [ContainX/docker-volume-netshare#79]
It looks like previous versions of netshare have an ARM build, but the latest doesn't seem to.

**Comment by gondor** [comment]
Ok I just released a new version and including ARM support (binary and .deb package).  See https://github.com/ContainX/docker-volume-netshare/releases

Please close if this is what you were looking for @Lindenk

**Comment by Lindenk** [comment]
Ah, perfect. That's what I was looking for. Thanks!
